/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        vb: {
          surface: "#12131a",
          "surface-low": "#1a1b22",
          "surface-container": "#1e1f27",
          "on-surface": "#e3e1ec",
          "on-surface-variant": "#cdc3d6",
          primary: "#d5baff",
          "primary-container": "#8e54e9",
          secondary: "#b2c5ff",
          neon: "#8e54e9",
          electric: "#4776e6",
          deep: "#0c0d14",
          outline: "#968d9f",
          "outline-variant": "#4b4454",
        },
        "outline-variant": "#4b4454",
        "secondary-fixed-dim": "#b2c5ff",
        "tertiary": "#ffb955",
        "secondary-fixed": "#dae2ff",
        "glass-surface": "rgba(255, 255, 255, 0.03)",
        "bg-deep": "#0c0d14",
        "on-secondary-container": "#b2c5ff",
        "on-surface-variant": "#cdc3d6",
        "inverse-on-surface": "#2f3038",
        "outline": "#968d9f",
        "inverse-primary": "#7639d0",
        "surface-container-high": "#292931",
        "surface-bright": "#383941",
        "on-primary-fixed-variant": "#5d15b7",
        "on-tertiary-fixed-variant": "#633f00",
        "on-secondary-fixed-variant": "#003fa3",
        "tertiary-fixed-dim": "#ffb955",
        "glass-border": "rgba(255, 255, 255, 0.12)",
        "primary-fixed": "#ecdcff",
        "surface-container-lowest": "#0d0e15",
        "on-tertiary-fixed": "#291800",
        "on-tertiary-container": "#fffeff",
        "surface-dim": "#12131a",
        "tertiary-container": "#a26a00",
        "error-container": "#93000a",
        "surface-tint": "#d5baff",
        "inverse-surface": "#e3e1ec",
        "primary-fixed-dim": "#d5baff",
        "secondary-container": "#054aba",
        "neon-purple": "#8e54e9",
        "background": "#12131a",
        "tertiary-fixed": "#ffddb4",
        "secondary": "#b2c5ff",
        "on-error": "#690005",
        "surface-container-highest": "#34343c",
        "error": "#ffb4ab",
        "on-background": "#e3e1ec",
        "surface-variant": "#34343c",
        "on-primary-container": "#fffeff",
        "on-surface": "#e3e1ec",
        "primary": "#d5baff",
        "surface-container": "#1e1f27",
        "on-error-container": "#ffdad6",
        "electric-blue": "#4776e6",
        "on-primary-fixed": "#270057",
        "surface": "#12131a",
        "on-secondary-fixed": "#001849",
        "on-secondary": "#002b74",
        "primary-container": "#8e54e9",
        "on-primary": "#42008a",
        "on-tertiary": "#452b00",
      },
      fontFamily: {
        sans: [
          "Hanken Grotesk",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "sans-serif",
        ],
        mono: ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
      },
      borderRadius: {
        vb: "0.5rem",
        "vb-md": "0.75rem",
        "vb-lg": "1rem",
        "vb-xl": "1.5rem",
      },
      boxShadow: {
        "vb-glow": "0 0 12px rgba(142, 84, 233, 0.4)",
        "vb-glow-strong": "0 0 16px rgba(142, 84, 233, 0.7)",
        "vb-elevated": "0 8px 32px rgba(0, 0, 0, 0.4)",
      },
      backgroundImage: {
        "vb-gradient": "linear-gradient(135deg, #8e54e9, #4776e6)",
      },
    },
  },
  plugins: [],
};
