import { createContext, useEffect, useState } from "react";

// Translation data
const translations = {
  en: {
    // Header
    searchPlaceholder: "Search people, posts, groups...",
    searching: "Searching...",
    noResults: "No results found for",
    users: "Users",
    posts: "Posts",
    themeStyle: "Theme Style",

    // Navigation
    home: "Home",
    profile: "Profile",
    messenger: "Messenger",
    notifications: "Notifications",
    groups: "Groups",
    events: "Events",
    friends: "Friends",
    video: "Video",
    story: "Story",
    playGame: "Play Game",
    store: "Store",
    source: "Library",

    // Common
    loading: "Loading ThoDev...",
    anonymous: "Anonymous",
    noContent: "No content",
    language: "Language",

    // Groups
    groupsCount: "Groups",
    searchGroup: "Search group...",
    createGroup: "Create Group",
    createNewGroup: "Create New Group",
    saveGroup : "Create",
    joinGroup: "Join Group",
    dateCreateGroup: "Date:",
    leaveGroup: "Leave Group",
    deleteGroup: "Delete Group",
    groupName: "Group Name",
    groupDescription: "Description",
    members: "Members",
    viewDetail: "View Detail",
    media: "Media",
    about: "About",

    //Menu Group Sidebar
    homeGroup: "Group Home",
    membersGroup: "Members",
    eventsGroup: "Events",
    mediaGroup: "Media",
    aboutGroup: "About Group",

     // Groups details header
    updateBanner: "Update Banner",
    invitemembers: "+ Invite Members",

    // Stories
    createStory: "Create Story",
    close: "Close",
    whatsYourStory: "What's your story title?",
    postStory: "Post Story",
    uploading: "Uploading…",
    noStories: "No stories yet. Click",
    toPostFirst: "to post your first one!",
    storyDeleted: "Story deleted",

    // Notifications
    markAsRead: "Mark as Read",
    deleteOldNotifications: "Delete old notifications (>3 days)",
    noUnreadNotifications: "No unread notifications",
    markedAsRead: "Marked as read",
    notificationsRead: "notification is read",

    // Messenger
    welcomeToMessenger: "Welcome to Messenger",
    selectChat: "Select a chat to start messaging",

    // Auth
    login: "Login",
    register: "Register",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    signUp: "Sign Up",
    signIn: "Sign In",
    signOut: "Sign Out",

    // Profile
    viewProfile: "View Profile",
    settings: "Settings",
    settingEyebrow: "Your space",
    settingTitle: "Settings & preferences",
    settingSubtitle: "Personalize ThoDev and manage your account in one place.",
    settingAppearance: "Appearance & language",
    settingAppearanceDescription: "Choose how ThoDev looks and which language it uses.",
    settingPrivacy: "Privacy",
    settingPrivacyDescription: "Control the default audience for your new posts.",
    settingNotifications: "Notifications",
    settingNotificationsDescription: "Choose which social updates you want to receive.",
    settingAccessibility: "Accessibility",
    settingAccessibilityDescription: "Make ThoDev more comfortable for you to use.",
    settingSecurity: "Account & security",
    settingSecurityDescription: "Protect your account and manage your sign-in.",
    settingTheme: "Display mode",
    settingLight: "Light",
    settingDark: "Dark",
    settingBackground: "Background color",
    settingBackgroundDescription: "This color is applied across your ThoDev workspace.",
    settingBackgroundDefault: "Default",
    settingBackgroundSky: "Sky",
    settingBackgroundLavender: "Lavender",
    settingBackgroundMint: "Mint",
    settingBackgroundWarm: "Warm",
    settingLanguage: "Display language",
    settingDefaultAudience: "Default post audience",
    settingDefaultAudienceDescription: "New posts will start with this audience. You can still change it per post.",
    settingPublicDescription: "Anyone on or off ThoDev can see your post.",
    settingFriendsDescription: "Only your ThoDev friends can see your post.",
    settingPrivateDescription: "Only you can see your post.",
    settingNotifyReactions: "Reactions",
    settingNotifyReactionsDescription: "When someone reacts to your post.",
    settingNotifyComments: "Comments",
    settingNotifyCommentsDescription: "When someone comments on your post.",
    settingNotifyFriends: "Friend requests",
    settingNotifyFriendsDescription: "New requests and friend confirmations.",
    settingNotifyMessages: "Messages",
    settingNotifyMessagesDescription: "New messages and conversation updates.",
    settingFontSize: "Text size",
    settingFontSmall: "Small",
    settingFontNormal: "Standard",
    settingFontLarge: "Large",
    settingReducedMotion: "Reduce motion",
    settingReducedMotionDescription: "Limits animations and moving effects throughout the app.",
    settingCompactMode: "Compact layout",
    settingCompactModeDescription: "Reduces spacing to show more content on screen.",
    settingChangePassword: "Change password",
    settingCurrentPassword: "Current password",
    settingNewPassword: "New password",
    settingConfirmNewPassword: "Confirm new password",
    settingShowPassword: "Show password",
    settingHidePassword: "Hide password",
    settingUpdatePassword: "Update password",
    settingSaving: "Saving...",
    settingPasswordTooShort: "The new password must be at least 6 characters.",
    settingPasswordMismatch: "The new passwords do not match.",
    settingPasswordProviderUnsupported: "This account does not use an email password.",
    settingPasswordChanged: "Password updated successfully.",
    settingCurrentPasswordWrong: "The current password is incorrect.",
    settingPasswordChangeFailed: "Unable to update the password. Please try again.",
    settingExternalAccount: "Account managed by an external provider",
    settingExternalAccountDescription: "Change your password through the provider you used to sign in.",
    settingLogout: "Sign out on this device",
    settingLogoutDescription: "You will need to sign in again to use ThoDev here.",
    settingLogoutConfirm: "Do you want to sign out on this device?",
    editProfile: "Edit Profile",
    updateProfile: "Update Profile",
    respond: "Respond",
    viewRespond: "View Respond",

    // Posts
    createPost: "Create Post",
    post: "Post",
    comment: "Comment",
    like: "Like",
    share: "Share",
    hidden: "Hidden",
    view: "View",
    writeComment: "Write comment...",
    editPost: "Edit",
    deletePost: "Delete",
    privatePost: "Private",
    love: "Love",
    haha: "Haha",
    wow: "Wow",
    sad: "Sad",
    angry: "Angry",
    savePost: "Save post",
    saved: "Saved",
    unsavePost: "Remove saved post",
    copyLink: "Copy link",
    copyContent: "Copy content",
    systemShare: "Share via device",
    shareToTimeline: "Share to profile",
    sharePost: "Share post",
    publicVisibility: "Public",
    friendsVisibility: "Friends",
    privateVisibility: "Only me",
    shareDescriptionPlaceholder: "Say something about this post...",
    tagFriends: "Tag friends",
    searchFriends: "Search friends...",
    loadingFriends: "Loading friends...",
    noFriendsFound: "No friends found",
    noFriendsToTag: "No friends available to tag",
    sharingNow: "Sharing...",
    shareNow: "Share now",
    vibookUser: "ThoDev user",
    sharedWith: "with",
    sharedPost: "Shared post",
    loadingOriginalPost: "Loading original post...",
    originalPostUnavailable: "The original post no longer exists or cannot be accessed.",
    vibookPost: "Post on ThoDev",
    loginToShare: "Please log in to share",
    loadFriendsFailed: "Unable to load friends",
    maxTaggedFriends: "You can tag up to 20 people",
    originalPostNotFound: "Original post not found",
    shareSuccess: "Shared to your profile",
    shareFailed: "Sharing failed",
    loginToSave: "Please log in to save posts",
    postUnsaved: "Post removed from saved items",
    postSaved: "Post saved",
    savePostFailed: "Unable to update saved posts",
    shareOpened: "Share dialog opened",
    copied: "Copied",
    shareActionFailed: "Unable to share this post",
    confirmDeletePost: "Delete this post?",
    cannotDeletePost: "You cannot delete this post",
    postDeleted: "Post deleted",
    deletePostFailed: "Unable to delete post",
    postTitleRequired: "Please enter a post title",
    postContentRequired: "Post content cannot be empty",
    postUpdated: "Post updated",
    updatePostFailed: "Unable to update post",
    reactionFailed: "Unable to react to this post",
    postTitlePlaceholder: "Post title",
    postContentPlaceholder: "Enter post content...",
    postGreeting: "Hello {name},",
    minuteAgo: "{count} min",
    hourAgo: "{count} hr",
    dayAgo: "{count} day",

    // Friends
    addFriend: "Add Friend",
    removeFriend: "Remove Friend",
    friendRequestSent: "Friend request sent",
    friendRequestAccepted: "Friend request accepted",
    myFriends: "My Friends",
    friendRequests: "Friend Requests",
    findFriends: "Find Friends",

    // Events
    createEvent: "Create Event",
    description: "Description",
    eventName: "Event Name",
    eventDate: "Event Date",
    startDateTime: "Start Date & Time",
    endDateTime: "End Date & Time",
    eventLocation: "Event Location",
    bannerImage: "Banner Image (URL)",
    createNewEvent: "Create New Event",
    updateEvent: "Update Event",
    eventNameRequired: "Event name and date cannot be empty",
    loginToCreateEvent: "Please log in to create an event",
    eventCreated: "Event created successfully!",
    eventCreateFailed: "Failed to create event",
    eventUpdated: "Event updated successfully!",
    eventUpdateFailed: "Failed to update event",
    loginToJoinEvent: "Please log in to join the event",
    joinedEvent: "Joined event successfully!",
    joinEventFailed: "Failed to join event",
    loginToLeaveEvent: "Please log in to leave the event",
    leftEvent: "Left event successfully!",
    leaveEventFailed: "Failed to leave event",
    onlyOwnerDelete: "Only the event owner can delete the event",
    eventDeleted: "Event deleted successfully!",
    eventDeleteFailed: "Failed to delete event",
    loginToViewEvents: "Please log in to view and join events",
    searchEvents: "Search events...",
    create: "Create",
    cancel: "Cancel",
    save: "Save",
    edit: "Edit",
    delete: "Delete",
    participants: "Participants",
    date: "Date:",
    location: "Location:",
    leaveEvent: "Leave Event",
    joinEvent: "Join Event",
    created: "Created:",
    eventNameHint: "Enter a memorable name for your event (recommended 5-80 characters).",
    startDateTimeHint: "Select the date and time when your event starts.",
    endDateTimeHint: "Select the date and time when your event ends.",
    locationHint: "Where is the event? (e.g., 'Room 101, building A' or 'Online via Zoom').",
    eventDescriptionHint: "Provide details about the event, agenda, topics, or target audience.",
    bannerImageHint: "Upload a banner photo. High-quality image, landscape orientation (recommended 16:9).",
    noEventsFound: "No events found. Create your first event!",
    unableToLoadEvents: "Unable to load events",
    eventChat: "Event chat",
    justNow: "Just now",
    enterEventName: "Enter event name",
    enterLocation: "Enter location (optional)",
    enterEventDescription: "Enter event description (optional)",
    eventDescription: "Description",
    dateAndTime: "Date & Time",
    eventsTitle: "Events",

    // Game
    gameInstructions: "Game Instructions",
    gameTitleCount: "Games",
    addNewgame: "Add New Game",
    gameTitle: "Title",
    descriptionGame: "Description",
    gameLink: "Game Link (URL)",
    gameImage: "Game Image (URL)",
    playNow: "Play Now",
    addGame: "Add Game",
    Nogamesfound: "No games found.",


    // Post creation
    whatsOnYourMind: "What's on your mind?",
    photoVideo: "Photo/Video",
    camera: "Camera",
    document: "Document",
    emoji: "Emoji",
    posting: "Posting...",
    mediaAttached: "Media attached",
    maxFilesReached: "Max files reached",
    cameraActive: "Camera active",
    switch: "Switch",
    capture: "Capture",
    searchEmoji: "Search emoji...",
    loginRequired: "Please log in to post",
    loginToReact: "Please log in to react",
    loginToAddFriend: "Please log in to send a friend request",
    loginToFollow: "Please log in to follow this user",
    loginToMessenger: "Please log in to use Messenger",
    loginToSettings: "Please log in to change account settings",
    loginToPrivateSettings: "Please log in to change privacy, notifications, or security settings",
    settingGuestHint: "You can change theme, language, and accessibility. Account settings require login.",
    settingLockedTitle: "Sign in required",
    settingLockedDescription: "This section is only available when you are logged in.",
    loginToViewFriends: "Please log in to view your friends",
    loginToViewFriendRequests: "Please log in to view friend requests",
    guestFriendsHint:
      "Browse people on ThoDev. Log in to see your friends and friend requests.",
    loginToContinue: "Please log in to continue",
    loginToastTitle: "Not signed in",
    loginToastDefaultDesc: "Sign in to ThoDev to sync your data",
    contentOrMediaRequired: "Please enter content or attach media",
    maxFilesLimit: "Maximum 5 files per post",
    postSuccess: "Post created successfully",
    postError: "Error creating post",
    cloudinaryConfigMissing: "Missing Cloudinary configuration in .env",
    photoCaptured: "Photo captured and added to post",
    cameraError: "Cannot open camera. Please check permissions",
    uploadFailed: "Upload failed: ",
    switchCamera: "Switch camera",
    capturePhoto: "Capture photo",
    attachedMedia: "Attached media",
    limitReached: "Limit reached",

    // Error messages
    error: "Error",
    success: "Success",
    warning: "Warning",
    info: "Info",

    // Loading states
    loadingText: "Loading...",
    saving: "Saving...",
    deleting: "Deleting...",

    // Profile specific
    userNotFound: "User not found",
    youHaventPostedYet: "You haven't posted yet",
    noPostsYet: "No posts yet",
    failedToSendFriendRequest: "Failed to send friend request.",
    friendRequestSentTo: "Friend request sent to {name}!",

    // Blog
    blog: "Blog",
    blogListTitle: "Blog Articles",
    blogSearchPlaceholder: "Search articles, tags, categories...",
    filterByCategory: "Filter by Category",
    filterByTag: "Filter by Tag",
    sortByNewest: "Newest",
    sortByOldest: "Oldest",
    readTime: "{time} min read",
    publishedOn: "Published on",
    views: "Views",
    addPost: "Add Post",
    adminDashboard: "Admin Dashboard",
    managePosts: "Manage Posts",
    manageCategories: "Manage Categories",
    manageTags: "Manage Tags",
    title: "Title",
    slug: "Slug (URL-friendly)",
    blogDescription: "Short Description",
    coverImage: "Cover Image",
    category: "Category",
    tags: "Tags",
    content: "Content",
    publish: "Publish",
    saveDraft: "Save as Draft",
    preview: "Preview",
    blogSave: "Save",
    blogCancel: "Cancel",
    confirmDelete: "Are you sure you want to delete this post?",
    blogPostDeleted: "Post deleted successfully",
    postDeleteFailed: "Failed to delete post",
    relatedPosts: "Related Posts",
    blogSharePost: "Share Post",
    selectCategory: "Select Category",
    newCategoryPlaceholder: "New category name...",
    newTagPlaceholder: "New tag name...",
    postCreated: "Post created successfully",
    titleHint: "Enter a catchy title that summarizes your content (recommended 10-70 characters).",
    slugHint: "URL-friendly path (e.g., 'my-first-post'). Auto-generated from the title.",
    descriptionHint: "A short summary shown on the blog list card (recommended 100-160 characters).",
    categoryHint: "Select a topic category or type a new one to add.",
    tagsHint: "Add keyword tags for searchability (e.g., react, js). Press enter or click Add. Max 5 tags.",
    coverImageHint: "High-quality banner image (recommended 16:9 aspect ratio).",
    contentHint: "Write your detailed blog post content using the rich text editor below.",

    // Sidebar
    logout: "Logout",
    logoutSuccess: "Logged out successfully",
    logoutFailed: "Failed to log out: ",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    expandSidebar: "Expand sidebar",
    collapseSidebar: "Collapse sidebar",

    // Store/Market
    storeTitle: "THODEV MARKET",
    searchProducts: "Search for products you want...",
    cart: "Cart",
    orders: "Orders",
    sellerChannel: "Seller Channel",
    categories: "Categories",
    allProducts: "All Products",
    latestProducts: "Latest Products",
    categoryTitle: "Category: {category}",
    productCount: "{count} products",
    noProductsFound: "No matching products found.",
    hot: "HOT",
    viewDetails: "View Details",
    loadingOrders: "Loading orders...",
    myOrders: "My Orders",
    all: "All",
    noOrdersInSection: "You have no orders in this section.",
    shopNow: "Shop now",
    buyAgain: "Buy again",
    categoryLabel: "Category:",
    default: "Default",
    quantity: "Quantity:",
    totalAmount: "Total:",
    pending: "Pending",
    shipped: "Shipped",
    delivered: "Delivered",
    cancelled: "Cancelled",

    addCart: "Add to Cart",
    byNow: "Buy Now",
    numberProduct: "Number",
    review: "Review",
    notReviewForProduct: "No reviews for this product",
    genuine: "Genuine Product",
    nationwideDelivery: "Nationwide Delivery",
    evaluate: "Evaluate",
    sold: "Sold",
    outOfStock: "Out of Stock",
    product: "Product",


  },
  vi: {
    // Blog
    blog: "Blog",
    blogListTitle: "Danh sách bài viết",
    blogSearchPlaceholder: "Tìm kiếm bài viết, thẻ, danh mục...",
    filterByCategory: "Lọc theo Danh mục",
    filterByTag: "Lọc theo Thẻ",
    sortByNewest: "Mới nhất",
    sortByOldest: "Cũ nhất",
    readTime: "{time} phút đọc",
    publishedOn: "Ngày đăng",
    views: "Lượt xem",
    addPost: "Thêm bài viết",
    adminDashboard: "Bảng điều khiển quản trị",
    managePosts: "Quản lý bài viết",
    manageCategories: "Quản lý Danh mục",
    manageTags: "Quản lý Thẻ",
    title: "Tiêu đề",
    slug: "Slug (thân thiện URL)",
    blogDescription: "Mô tả ngắn",
    coverImage: "Ảnh bìa",
    category: "Danh mục",
    tags: "Thẻ",
    content: "Nội dung",
    publish: "Xuất bản",
    saveDraft: "Lưu bản nháp",
    preview: "Xem trước",
    blogSave: "Lưu",
    blogCancel: "Hủy",
    confirmDelete: "Bạn có chắc muốn xóa bài viết này?",
    blogPostDeleted: "Đã xóa bài viết thành công",
    postDeleteFailed: "Không thể xóa bài viết",
    relatedPosts: "Bài viết liên quan",
    blogSharePost: "Chia sẻ bài viết",
    selectCategory: "Chọn danh mục",
    newCategoryPlaceholder: "Tên danh mục mới...",
    newTagPlaceholder: "Tên thẻ mới...",
    postCreated: "Tạo bài viết thành công",
    postError: "Lỗi khi lưu bài viết",
    uploadFailed: "Tải lên thất bại: ",
    titleHint: "Nhập tiêu đề hấp dẫn, tóm tắt nội dung (nên từ 10 - 70 ký tự).",
    slugHint: "Đường dẫn thân thiện (ví dụ: 'bai-viet-dau-tien'). Tự động tạo từ tiêu đề.",
    descriptionHint: "Tóm tắt ngắn hiển thị trên thẻ danh sách blog (nên từ 100 - 160 ký tự).",
    categoryHint: "Chọn chủ đề cho bài viết hoặc nhập tên để thêm danh mục mới.",
    tagsHint: "Thêm các từ khóa tìm kiếm (ví dụ: react, js). Nhấn nút Thêm hoặc Enter. Tối đa 5 thẻ.",
    coverImageHint: "Hình ảnh biểu ngữ chất lượng cao (khuyên dùng tỷ lệ 16:9).",
    contentHint: "Viết nội dung chi tiết bài viết của bạn bằng trình soạn thảo bên dưới.",

    // Header
    searchPlaceholder: "Tìm kiếm người dùng, bài viết, nhóm...",
    searching: "Đang tìm kiếm...",
    noResults: "Không tìm thấy kết quả cho",
    users: "Người dùng",
    posts: "Bài viết",
    themeStyle: "Kiểu giao diện",

    // Navigation
    home: "Trang chủ",
    profile: "Hồ sơ",
    messenger: "Tin nhắn",
    notifications: "Thông báo",
    groups: "Nhóm",
    events: "Sự kiện",
    friends: "Bạn bè",
    video: "Video",
    story: "Story",
    playGame: "Chơi game",
    store: "Cửa hàng",
    source: "Kho tài liệu",

    // Common
    loading: "Đang tải ThoDev...",
    anonymous: "Ẩn danh",
    noContent: "Không có nội dung",
    language: "Ngôn ngữ",

    // Groups
    searchGroup: "Tìm kiếm nhóm...",
    groupsCount: "Nhóm",
    createGroup: "Tạo nhóm",
    createNewGroup: "Tạo nhóm mới",
    saveGroup : "Tạo",
    joinGroup: "Tham gia nhóm",
    dateCreateGroup: "Ngày:",
    leaveGroup: "Rời nhóm",
    editGroup: "Chỉnh sửa nhóm",
    deleteGroup: "Xóa nhóm",
    groupName: "Tên nhóm",
    groupDescription: "Mô tả",
    members: "Thành viên",
    viewDetail: "Xem chi tiết",
    media: "Media",
    about: "Giới thiệu",

    //Menu Group Sidebar
    homeGroup: "Trang nhóm",
    membersGroup: "Thành viên",
    eventsGroup: "Sự kiện",
    mediaGroup: "Media",
    aboutGroup: "Giới thiệu nhóm",

     // Groups details header
    updateBanner: "Cập nhật banner",
    invitemembers: "+ Mời thành viên",


    // Stories
    createStory: "Tạo story",
    whatsYourStory: "Tiêu đề story của bạn?",
    postStory: "Đăng story",
    uploading: "Đang tải lên…",
    noStories: "Chưa có story nào. Nhấn",
    toPostFirst: "để đăng story đầu tiên!",
    storyDeleted: "Đã xóa story",

    // Notifications
    markAsRead: "Đánh dấu đã đọc",
    deleteOldNotifications: "Xóa thông báo cũ (>3 ngày)",
    noUnreadNotifications: "Không có thông báo chưa đọc",
    markedAsRead: "Đã đánh dấu đã đọc",
    notificationsRead: "thông báo đã đọc",

    // Messenger
    welcomeToMessenger: "Chào mừng đến Messenger",
    selectChat: "Chọn cuộc trò chuyện để bắt đầu nhắn tin",

    // Auth
    login: "Đăng nhập",
    register: "Đăng ký",
    email: "Email",
    password: "Mật khẩu",
    confirmPassword: "Xác nhận mật khẩu",
    signUp: "Đăng ký",
    signIn: "Đăng nhập",
    signOut: "Đăng xuất",

    // Profile
    viewProfile: "Xem hồ sơ",
    settings: "Cài đặt",
    settingEyebrow: "Không gian của bạn",
    settingTitle: "Cài đặt & tùy chọn",
    settingSubtitle: "Cá nhân hóa ThoDev và quản lý tài khoản tại một nơi.",
    settingAppearance: "Giao diện & ngôn ngữ",
    settingAppearanceDescription: "Chọn cách ThoDev hiển thị và ngôn ngữ bạn muốn sử dụng.",
    settingPrivacy: "Quyền riêng tư",
    settingPrivacyDescription: "Kiểm soát đối tượng mặc định cho bài viết mới.",
    settingNotifications: "Thông báo",
    settingNotificationsDescription: "Chọn những cập nhật xã hội bạn muốn nhận.",
    settingAccessibility: "Khả năng tiếp cận",
    settingAccessibilityDescription: "Điều chỉnh ThoDev để sử dụng thoải mái hơn.",
    settingSecurity: "Tài khoản & bảo mật",
    settingSecurityDescription: "Bảo vệ tài khoản và quản lý việc đăng nhập.",
    settingTheme: "Chế độ hiển thị",
    settingLight: "Sáng",
    settingDark: "Tối",
    settingBackground: "Màu nền",
    settingBackgroundDescription: "Màu này được áp dụng cho toàn bộ không gian ThoDev.",
    settingBackgroundDefault: "Mặc định",
    settingBackgroundSky: "Xanh trời",
    settingBackgroundLavender: "Oải hương",
    settingBackgroundMint: "Bạc hà",
    settingBackgroundWarm: "Ấm áp",
    settingLanguage: "Ngôn ngữ hiển thị",
    settingDefaultAudience: "Đối tượng mặc định của bài viết",
    settingDefaultAudienceDescription: "Bài viết mới sẽ dùng lựa chọn này. Bạn vẫn có thể đổi riêng từng bài.",
    settingPublicDescription: "Mọi người trong hoặc ngoài ThoDev đều có thể xem.",
    settingFriendsDescription: "Chỉ bạn bè trên ThoDev có thể xem.",
    settingPrivateDescription: "Chỉ mình bạn có thể xem.",
    settingNotifyReactions: "Cảm xúc",
    settingNotifyReactionsDescription: "Khi ai đó bày tỏ cảm xúc với bài viết của bạn.",
    settingNotifyComments: "Bình luận",
    settingNotifyCommentsDescription: "Khi ai đó bình luận bài viết của bạn.",
    settingNotifyFriends: "Lời mời kết bạn",
    settingNotifyFriendsDescription: "Lời mời mới và xác nhận kết bạn.",
    settingNotifyMessages: "Tin nhắn",
    settingNotifyMessagesDescription: "Tin nhắn mới và cập nhật cuộc trò chuyện.",
    settingFontSize: "Cỡ chữ",
    settingFontSmall: "Nhỏ",
    settingFontNormal: "Tiêu chuẩn",
    settingFontLarge: "Lớn",
    settingReducedMotion: "Giảm chuyển động",
    settingReducedMotionDescription: "Hạn chế hiệu ứng chuyển động và hoạt ảnh trong ứng dụng.",
    settingCompactMode: "Bố cục gọn",
    settingCompactModeDescription: "Giảm khoảng cách để hiển thị nhiều nội dung hơn.",
    settingChangePassword: "Đổi mật khẩu",
    settingCurrentPassword: "Mật khẩu hiện tại",
    settingNewPassword: "Mật khẩu mới",
    settingConfirmNewPassword: "Xác nhận mật khẩu mới",
    settingShowPassword: "Hiện mật khẩu",
    settingHidePassword: "Ẩn mật khẩu",
    settingUpdatePassword: "Cập nhật mật khẩu",
    settingSaving: "Đang lưu...",
    settingPasswordTooShort: "Mật khẩu mới phải có ít nhất 6 ký tự.",
    settingPasswordMismatch: "Mật khẩu mới không khớp.",
    settingPasswordProviderUnsupported: "Tài khoản này không sử dụng mật khẩu email.",
    settingPasswordChanged: "Đã cập nhật mật khẩu thành công.",
    settingCurrentPasswordWrong: "Mật khẩu hiện tại không đúng.",
    settingPasswordChangeFailed: "Không thể cập nhật mật khẩu. Vui lòng thử lại.",
    settingExternalAccount: "Tài khoản do nhà cung cấp bên ngoài quản lý",
    settingExternalAccountDescription: "Hãy đổi mật khẩu tại nhà cung cấp bạn đã dùng để đăng nhập.",
    settingLogout: "Đăng xuất trên thiết bị này",
    settingLogoutDescription: "Bạn sẽ cần đăng nhập lại để sử dụng ThoDev tại đây.",
    settingLogoutConfirm: "Bạn có muốn đăng xuất trên thiết bị này không?",
    editProfile: "Chỉnh sửa hồ sơ",
    updateProfile: "Cập nhật hồ sơ",

    // Posts
    createPost: "Tạo bài viết",
    post: "Đăng",
    comment: "Bình luận",
    like: "Thích",
    share: "Chia sẻ",
    respond: "Phản hồi",
    viewRespond: "Xem phản hồi",
    hidden: "Ẩn",
    view: "Xem",
    writeComment: "Viết bình luận...",
    editPost: "Chỉnh sửa",
    deletePost: "Xóa",
    privatePost: "Riêng tư",
    love: "Yêu thích",
    haha: "Haha",
    wow: "Wow",
    sad: "Buồn",
    angry: "Phẫn nộ",
    savePost: "Lưu bài viết",
    saved: "Đã lưu",
    unsavePost: "Bỏ lưu bài viết",
    copyLink: "Sao chép liên kết",
    copyContent: "Sao chép nội dung",
    systemShare: "Chia sẻ qua thiết bị",
    shareToTimeline: "Chia sẻ lên trang cá nhân",
    sharePost: "Chia sẻ bài viết",
    publicVisibility: "Công khai",
    friendsVisibility: "Bạn bè",
    privateVisibility: "Chỉ mình tôi",
    shareDescriptionPlaceholder: "Hãy nói gì đó về bài viết này...",
    tagFriends: "Gắn thẻ bạn bè",
    searchFriends: "Tìm bạn bè...",
    loadingFriends: "Đang tải danh sách bạn bè...",
    noFriendsFound: "Không tìm thấy bạn bè",
    noFriendsToTag: "Chưa có bạn bè để gắn thẻ",
    sharingNow: "Đang chia sẻ...",
    shareNow: "Chia sẻ ngay",
    vibookUser: "Người dùng ThoDev",
    sharedWith: "cùng với",
    sharedPost: "Bài viết được chia sẻ",
    loadingOriginalPost: "Đang tải bài viết gốc...",
    originalPostUnavailable: "Bài viết gốc không còn tồn tại hoặc không thể truy cập.",
    vibookPost: "Bài viết trên ThoDev",
    loginToShare: "Bạn cần đăng nhập để chia sẻ",
    loadFriendsFailed: "Không thể tải danh sách bạn bè",
    maxTaggedFriends: "Bạn chỉ có thể gắn thẻ tối đa 20 người",
    originalPostNotFound: "Không tìm thấy bài viết gốc",
    shareSuccess: "Đã chia sẻ lên trang cá nhân",
    shareFailed: "Chia sẻ thất bại",
    loginToSave: "Bạn cần đăng nhập để lưu bài viết",
    postUnsaved: "Đã bỏ lưu bài viết",
    postSaved: "Đã lưu bài viết",
    savePostFailed: "Không thể cập nhật bài viết đã lưu",
    shareOpened: "Đã mở chia sẻ",
    copied: "Đã sao chép",
    shareActionFailed: "Không thể chia sẻ bài viết",
    confirmDeletePost: "Xóa bài viết này?",
    cannotDeletePost: "Bạn không thể xóa bài viết này",
    postDeleted: "Đã xóa bài viết",
    deletePostFailed: "Lỗi khi xóa bài viết",
    postTitleRequired: "Vui lòng nhập tiêu đề bài viết",
    postContentRequired: "Nội dung không được để trống",
    postUpdated: "Đã cập nhật bài viết",
    updatePostFailed: "Lỗi khi lưu thay đổi",
    reactionFailed: "Không thể thả cảm xúc",
    postTitlePlaceholder: "Tiêu đề bài viết",
    postContentPlaceholder: "Nhập nội dung bài viết...",
    postGreeting: "Xin chào {name},",
    minuteAgo: "{count} phút",
    hourAgo: "{count} giờ",
    dayAgo: "{count} ngày",


    // Friends
    addFriend: "Thêm bạn",
    removeFriend: "Xóa bạn",
    friendRequestSent: "Đã gửi lời mời kết bạn",
    friendRequestAccepted: "Đã chấp nhận lời mời kết bạn",
    myFriends: "Bạn bè của tôi",
    friendRequests: "Lời mời kết bạn",
    findFriends: "Tìm bạn bè",

    // Events
    createEvent: "Tạo sự kiện",
    description: "Mô tả",
    eventName: "Tên sự kiện",
    eventDate: "Ngày sự kiện",
    startDateTime: "Ngày giờ bắt đầu",
    endDateTime: "Ngày giờ kết thúc",
    eventLocation: "Địa điểm sự kiện",
    bannerImage: "Ảnh banner (URL)",
    createNewEvent: "Tạo sự kiện mới",
    updateEvent: "Cập nhật sự kiện",
    eventNameRequired: "Tên sự kiện và ngày không được để trống",
    loginToCreateEvent: "Vui lòng đăng nhập để tạo sự kiện",
    eventCreated: "Tạo sự kiện thành công!",
    eventCreateFailed: "Tạo sự kiện thất bại",
    eventUpdated: "Cập nhật sự kiện thành công!",
    eventUpdateFailed: "Cập nhật sự kiện thất bại",
    loginToJoinEvent: "Vui lòng đăng nhập để tham gia sự kiện",
    joinedEvent: "Tham gia sự kiện thành công!",
    joinEventFailed: "Tham gia sự kiện thất bại",
    loginToLeaveEvent: "Vui lòng đăng nhập để rời sự kiện",
    leftEvent: "Rời sự kiện thành công!",
    leaveEventFailed: "Rời sự kiện thất bại",
    onlyOwnerDelete: "Chỉ chủ sở hữu mới có thể xóa sự kiện",
    eventDeleted: "Xóa sự kiện thành công!",
    eventDeleteFailed: "Xóa sự kiện thất bại",
    loginToViewEvents: "Vui lòng đăng nhập để xem và tham gia sự kiện",
    searchEvents: "Tìm kiếm sự kiện...",
    create: "Tạo",
    cancel: "Hủy",
    save: "Lưu",
    edit: "Sửa",
    delete: "Xóa",
    participants: "Người tham gia",
    date: "Ngày: ",
    location: "Địa điểm:",
    leaveEvent: "Rời sự kiện",
    joinEvent: "Tham gia sự kiện",
    created: "Đã tạo:",
    eventNameHint: "Nhập tên sự kiện ngắn gọn, dễ nhớ (khuyên dùng từ 5 - 80 ký tự).",
    startDateTimeHint: "Chọn ngày và giờ bắt đầu diễn ra sự kiện.",
    endDateTimeHint: "Chọn ngày và giờ kết thúc sự kiện.",
    locationHint: "Địa điểm diễn ra sự kiện (ví dụ: 'Phòng 101, tòa nhà A' hoặc 'Online qua Zoom').",
    eventDescriptionHint: "Mô tả chi tiết về sự kiện, nội dung chương trình, chủ đề thảo luận hoặc đối tượng tham gia.",
    bannerImageHint: "Tải ảnh biểu ngữ đại diện. Hình ảnh chất lượng cao, khổ ngang (khuyên dùng 16:9).",
    noEventsFound: "Không tìm thấy sự kiện nào. Tạo sự kiện đầu tiên của bạn!",
    unableToLoadEvents: "Không thể tải sự kiện",
    eventChat: "Trò chuyện sự kiện",
    eventsTitle: "Sự kiện",
    justNow: "Vừa xong",
    dateAndTime: "Ngày & Giờ",

    // Game
    gameInstructions: "Hướng dẫn chơi",
    gameTitleCount: "Trò Chơi",
    addGame: "Tạo game",
    addNewgame: "Thêm Trò Chơi Mới",
    gameTitle: "Tiêu Đề",
    descriptionGame: "Mô Tả",
    gameLink: "Liên Kết Trò Chơi (URL)",
    gameImage: "Ảnh Trò Chơi (URL)",
    playNow: "Chơi Ngay",
    Nogamesfound: "Không tìm thấy trò chơi nào.",
    

    // Post creation
    whatsOnYourMind: "Bạn đang nghĩ gì thế?",
    photoVideo: "Ảnh/Video",
    camera: "Camera",
    document: "Tài liệu",
    emoji: "Cảm xúc",
    posting: "Đang đăng...",
    mediaAttached: "Đã đính kèm media",
    maxFilesReached: "Đã đạt giới hạn tệp tin",
    cameraActive: "Camera đang hoạt động",
    switch: "Đổi",
    capture: "Chụp",
    searchEmoji: "Tìm emoji...",
    loginRequired: "Vui lòng đăng nhập để đăng bài",
    loginToReact: "Vui lòng đăng nhập để thả cảm xúc",
    loginToAddFriend: "Vui lòng đăng nhập để gửi lời mời kết bạn",
    loginToFollow: "Vui lòng đăng nhập để theo dõi người dùng này",
    loginToMessenger: "Vui lòng đăng nhập để nhắn tin",
    loginToSettings: "Vui lòng đăng nhập để chỉnh cài đặt tài khoản",
    loginToPrivateSettings:
      "Vui lòng đăng nhập để chỉnh quyền riêng tư, thông báo hoặc bảo mật",
    settingGuestHint:
      "Bạn có thể đổi giao diện, ngôn ngữ và khả năng tiếp cận. Cài đặt tài khoản cần đăng nhập.",
    settingLockedTitle: "Cần đăng nhập",
    settingLockedDescription: "Mục này chỉ dành cho tài khoản đã đăng nhập.",
    loginToViewFriends: "Vui lòng đăng nhập để xem bạn bè của bạn",
    loginToViewFriendRequests: "Vui lòng đăng nhập để xem lời mời kết bạn",
    guestFriendsHint:
      "Bạn có thể tìm người dùng trên ThoDev. Đăng nhập để xem bạn bè và lời mời kết bạn.",
    loginToContinue: "Vui lòng đăng nhập để tiếp tục",
    loginToastTitle: "Chưa đăng nhập",
    loginToastDefaultDesc: "Đăng nhập ThoDev để đồng bộ dữ liệu",
    contentOrMediaRequired: "Vui lòng nhập nội dung hoặc đính kèm media",
    maxFilesLimit: "Tối đa 5 tệp mỗi bài viết",
    unsupportedFormat: "Định dạng không hỗ trợ: ",
    fileTooLarge: "Tệp quá lớn ",
    postSuccess: "Đăng bài thành công",
    cloudinaryConfigMissing: "Thiếu cấu hình Cloudinary trong .env",
    photoCaptured: "Ảnh đã được chụp và thêm vào bài viết",
    cameraError: "Không mở được camera. Vui lòng kiểm tra quyền",
    switchCamera: "Chuyển camera",
    close: "Đóng",
    capturePhoto: "Chụp ảnh",

    // Error messages
    error: "Lỗi",
    success: "Thành công",
    warning: "Cảnh báo",
    info: "Thông tin",

    // Loading states
    loadingText: "Đang tải...",
    saving: "Đang lưu...",
    deleting: "Đang xóa...",

    // Profile specific
    userNotFound: "Không tìm thấy người dùng",
    youHaventPostedYet: "Bạn chưa đăng bài nào",
    noPostsYet: "Chưa có bài viết nào",
    failedToSendFriendRequest: "Gửi lời mời kết bạn thất bại.",
    friendRequestSentTo: "Đã gửi lời mời kết bạn đến {name}!",

    // Sidebar
    logout: "Đăng xuất",
    logoutSuccess: "Đăng xuất thành công",
    logoutFailed: "Đăng xuất thất bại: ",
    openMenu: "Mở menu",
    closeMenu: "Đóng menu",
    expandSidebar: "Mở rộng sidebar",
    collapseSidebar: "Thu gọn sidebar",

    // Store/Market
    storeTitle: "THODEV MARKET",
    searchProducts: "Tìm sản phẩm bạn mong muốn...",
    cart: "Giỏ hàng",
    orders: "Đơn hàng",
    sellerChannel: "Kênh người bán",
    categories: "Danh mục",
    allProducts: "Tất cả sản phẩm",
    latestProducts: "Sản phẩm mới nhất",
    categoryTitle: "Danh mục: {category}",
    productCount: "{count} sản phẩm",
    noProductsFound: "Không tìm thấy sản phẩm nào phù hợp.",
    hot: "HOT",
    viewDetails: "Xem chi tiết",
    loadingOrders: "Đang tải đơn hàng...",
    myOrders: "Đơn hàng của tôi",
    all: "Tất cả",
    noOrdersInSection: "Bạn chưa có đơn hàng nào trong mục này.",
    shopNow: "Mua sắm ngay",
    buyAgain: "Mua lại",
    categoryLabel: "Phân loại:",
    default: "Mặc định",
    quantity: "Số lượng:",
    totalAmount: "Thành tiền:",
    pending: "Chờ xử lý",
    shipped: "Đang giao",
    delivered: "Đã giao",
    cancelled: "Đã hủy",

    addCart: "Thêm vào giỏ",
    byNow: "Mua ngay",
    numberProduct: "Số lượng",
    review: "Đánh giá",
    notReviewForProduct: "Chưa có đánh giá cho sản phẩm này",
    genuine: "Sản phẩm chính hãng",
    nationwideDelivery: "Giao hàng toàn quốc",
    evaluate: "Đánh giá",
    sold: "Đã bán",
    outOfStock: "Hết hàng",
    product: "Sản phẩm",
  },
  ja: {
    // Header
    searchPlaceholder: "人、投稿、グループを検索...",
    searching: "検索中...",
    noResults: "の検索結果が見つかりません",
    users: "ユーザー",
    posts: "投稿",
    themeStyle: "テーマスタイル",

    // Navigation
    home: "ホーム",
    profile: "プロフィール",
    messenger: "メッセージ",
    notifications: "通知",
    groups: "グループ",
    events: "イベント",
    friends: "友達",
    video: "ビデオ",
    story: "ストーリー",
    playGame: "ゲーム",
    store: "ストア",

    // Common
    loading: "ThoDevを読み込み中...",
    anonymous: "匿名",
    noContent: "コンテンツなし",
    language: "言語",

    // Groups
    searchGroup: "グループを検索...",
    groupsCount: "グループ",
    createGroup: "グループ作成",
    createNewGroup: "新しいグループを作成",
    joinGroup: "グループ参加",
    saveGroup : "作成",
    dateCreateGroup: "日付:",
    leaveGroup: "グループ退出",
    deleteGroup: "グループ削除",
    editGroup: "グループ編集",
    groupName: "グループ名",
    groupDescription: "説明",
    members: "メンバー",
    viewDetail: "詳細を見る",
    media: "メディア",
    about: "について",

    // Groups details header
    updateBanner: "バナーを更新",
    invitemembers: "+メンバーを招待",

    //Menu Group Sidebar
    homeGroup: "グループホーム",
    membersGroup: "メンバー",
    eventsGroup: "イベント",
    mediaGroup: "メディア",
    aboutGroup: "グループについて",

    groupMembers: "グループメンバー",
    
    //introduction
    introduction: "紹介",
    suggest: "提案",
    
    // Members
    notFindMember: "メンバーが見つかりません",

    serachMembersGroup: "メンバーを検索...",
    noMembersFound: "メンバーが見つかりません",
    memberCount: "メンバー数",

    //Create group
    youMean: "あなたが意味するのは？",
    publicGroup: "パブリックグループ",
    privateGroup: "プライベートグループ",
    privacy: "プライバシー",
    anyoneCanFind: "誰でもグループを見つけて参加できます",
    onlyInvitedCanJoin: "招待されたメンバーのみが参加できます",
    create: "作成",
    creating: "作成中...",

    //Group media
    noMediaFound: "メディアが見つかりません",



    // Stories
    createStory: "ストーリー作成",
    whatsYourStory: "ストーリーのタイトルは何ですか？",
    postStory: "ストーリーを投稿",
    uploading: "アップロード中…",
    noStories: "まだストーリーがありません。クリック",
    toPostFirst: "して最初のストーリーを投稿！",
    storyDeleted: "ストーリーが削除されました",

    // Notifications
    markAsRead: "既読にする",
    deleteOldNotifications: "古い通知を削除（>3日）",
    noUnreadNotifications: "未読通知なし",
    markedAsRead: "既読にしました",
    notificationsRead: "件の通知を既読",

    // Messenger
    welcomeToMessenger: "Messengerへようこそ",
    selectChat: "メッセージを開始するにはチャットを選択",

    // Auth
    login: "ログイン",
    register: "登録",
    email: "メール",
    password: "パスワード",
    confirmPassword: "パスワード確認",
    signUp: "サインアップ",
    signIn: "サインイン",
    signOut: "サインアウト",

    // Profile
    viewProfile: "プロフィールを見る",
    settings: "設定",
    settingEyebrow: "あなたのスペース",
    settingTitle: "設定と環境設定",
    settingSubtitle: "ThoDevの表示とアカウントを一か所で管理します。",
    settingAppearance: "外観と言語",
    settingAppearanceDescription: "ThoDevの表示方法と言語を選択します。",
    settingPrivacy: "プライバシー",
    settingPrivacyDescription: "新しい投稿のデフォルト公開範囲を管理します。",
    settingNotifications: "通知",
    settingNotificationsDescription: "受け取りたいソーシャル通知を選択します。",
    settingAccessibility: "アクセシビリティ",
    settingAccessibilityDescription: "ThoDevをより快適に使えるよう調整します。",
    settingSecurity: "アカウントとセキュリティ",
    settingSecurityDescription: "アカウントとログインを安全に管理します。",
    settingTheme: "表示モード",
    settingLight: "ライト",
    settingDark: "ダーク",
    settingBackground: "背景色",
    settingBackgroundDescription: "ThoDev全体に適用する背景色です。",
    settingBackgroundDefault: "標準",
    settingBackgroundSky: "スカイ",
    settingBackgroundLavender: "ラベンダー",
    settingBackgroundMint: "ミント",
    settingBackgroundWarm: "ウォーム",
    settingLanguage: "表示言語",
    settingDefaultAudience: "投稿のデフォルト公開範囲",
    settingDefaultAudienceDescription: "新しい投稿に適用されます。投稿ごとに変更できます。",
    settingPublicDescription: "ThoDev内外のすべての人が閲覧できます。",
    settingFriendsDescription: "ThoDevの友達だけが閲覧できます。",
    settingPrivateDescription: "自分だけが閲覧できます。",
    settingNotifyReactions: "リアクション",
    settingNotifyReactionsDescription: "投稿にリアクションがあったとき。",
    settingNotifyComments: "コメント",
    settingNotifyCommentsDescription: "投稿にコメントがあったとき。",
    settingNotifyFriends: "友達リクエスト",
    settingNotifyFriendsDescription: "新しいリクエストと友達の承認。",
    settingNotifyMessages: "メッセージ",
    settingNotifyMessagesDescription: "新しいメッセージと会話の更新。",
    settingFontSize: "文字サイズ",
    settingFontSmall: "小",
    settingFontNormal: "標準",
    settingFontLarge: "大",
    settingReducedMotion: "動きを減らす",
    settingReducedMotionDescription: "アニメーションや動く効果を抑えます。",
    settingCompactMode: "コンパクト表示",
    settingCompactModeDescription: "間隔を狭めてより多くの内容を表示します。",
    settingChangePassword: "パスワードを変更",
    settingCurrentPassword: "現在のパスワード",
    settingNewPassword: "新しいパスワード",
    settingConfirmNewPassword: "新しいパスワードを確認",
    settingShowPassword: "パスワードを表示",
    settingHidePassword: "パスワードを隠す",
    settingUpdatePassword: "パスワードを更新",
    settingSaving: "保存中...",
    settingPasswordTooShort: "新しいパスワードは6文字以上必要です。",
    settingPasswordMismatch: "新しいパスワードが一致しません。",
    settingPasswordProviderUnsupported: "このアカウントはメールパスワードを使用していません。",
    settingPasswordChanged: "パスワードを更新しました。",
    settingCurrentPasswordWrong: "現在のパスワードが正しくありません。",
    settingPasswordChangeFailed: "パスワードを更新できませんでした。もう一度お試しください。",
    settingExternalAccount: "外部プロバイダーで管理されているアカウント",
    settingExternalAccountDescription: "ログインに使用したプロバイダーでパスワードを変更してください。",
    settingLogout: "この端末からログアウト",
    settingLogoutDescription: "この端末でThoDevを使うには再ログインが必要です。",
    settingLogoutConfirm: "この端末からログアウトしますか？",
    editProfile: "プロフィール編集",
    updateProfile: "プロフィール更新",

    // Posts
    createPost: "投稿作成",
    post: "投稿",
    comment: "コメント",
    like: "いいね",
    share: "シェア",
    respond: "返信",
    hidden: "非表示",
    view: "見る",
    writeComment: "コメントを書く...",
    editPost: "編集",
    deletePost: "削除",
    privatePost: "非公開",
    love: "大好き",
    haha: "面白いね",
    wow: "すごいね",
    sad: "悲しいね",
    angry: "ひどいね",
    savePost: "投稿を保存",
    saved: "保存済み",
    unsavePost: "保存を解除",
    copyLink: "リンクをコピー",
    copyContent: "内容をコピー",
    systemShare: "デバイスで共有",
    shareToTimeline: "プロフィールにシェア",
    sharePost: "投稿をシェア",
    publicVisibility: "公開",
    friendsVisibility: "友達",
    privateVisibility: "自分のみ",
    shareDescriptionPlaceholder: "この投稿について何か書く...",
    tagFriends: "友達をタグ付け",
    searchFriends: "友達を検索...",
    loadingFriends: "友達を読み込み中...",
    noFriendsFound: "友達が見つかりません",
    noFriendsToTag: "タグ付けできる友達がいません",
    sharingNow: "シェア中...",
    shareNow: "今すぐシェア",
    vibookUser: "ThoDevユーザー",
    sharedWith: "一緒に",
    sharedPost: "シェアされた投稿",
    loadingOriginalPost: "元の投稿を読み込み中...",
    originalPostUnavailable: "元の投稿が存在しないか、アクセスできません。",
    vibookPost: "ThoDevの投稿",
    loginToShare: "シェアするにはログインしてください",
    loadFriendsFailed: "友達リストを読み込めません",
    maxTaggedFriends: "タグ付けできるのは最大20人です",
    originalPostNotFound: "元の投稿が見つかりません",
    shareSuccess: "プロフィールにシェアしました",
    shareFailed: "シェアに失敗しました",
    loginToSave: "投稿を保存するにはログインしてください",
    postUnsaved: "保存を解除しました",
    postSaved: "投稿を保存しました",
    savePostFailed: "保存済み投稿を更新できません",
    shareOpened: "共有画面を開きました",
    copied: "コピーしました",
    shareActionFailed: "投稿をシェアできません",
    confirmDeletePost: "この投稿を削除しますか？",
    cannotDeletePost: "この投稿は削除できません",
    postDeleted: "投稿を削除しました",
    deletePostFailed: "投稿を削除できません",
    postTitleRequired: "投稿タイトルを入力してください",
    postContentRequired: "投稿内容を入力してください",
    postUpdated: "投稿を更新しました",
    updatePostFailed: "投稿を更新できません",
    reactionFailed: "リアクションできません",
    postTitlePlaceholder: "投稿タイトル",
    postContentPlaceholder: "投稿内容を入力...",
    postGreeting: "{name}さん、",
    minuteAgo: "{count}分",
    hourAgo: "{count}時間",
    dayAgo: "{count}日",

    // Friends
    addFriend: "友達追加",
    removeFriend: "友達削除",
    friendRequestSent: "友達リクエスト送信済み",
    friendRequestAccepted: "友達リクエスト承認済み",
    myFriends: "マイフレンド",
    friendRequests: "フレンドリクエスト",
    findFriends: "フレンドを探す",

    // Events
    createEvent: "イベント作成",
    description: "説明",
    eventName: "イベント名",
    eventDate: "イベント日",
    eventLocation: "イベント場所",
    createNewEvent: "新しいイベントを作成",
    updateEvent: "イベントを更新",
    eventNameRequired: "イベント名と日付は必須です",
    loginToCreateEvent: "イベントを作成するにはログインしてください",
    eventCreated: "イベントが作成されました！",
    eventCreateFailed: "イベントの作成に失敗しました",
    eventUpdated: "イベントが更新されました！",
    eventUpdateFailed: "イベントの更新に失敗しました",
    loginToJoinEvent: "イベントに参加するにはログインしてください",
    joinedEvent: "イベントに参加しました！",
    joinEventFailed: "イベントへの参加に失敗しました",
    loginToLeaveEvent: "イベントを離れるにはログインしてください",
    leftEvent: "イベントを離れました！",
    leaveEventFailed: "イベントからの離脱に失敗しました",
    onlyOwnerDelete: "イベントオーナーのみがイベントを削除できます",
    onlyOwnerCanDeleteEvent: "イベントオーナーのみがイベントを削除できます",
    eventDeleted: "イベントが削除されました！",
    eventDeleteFailed: "イベントの削除に失敗しました",
    loginToViewEvents: "イベントを表示して参加するにはログインしてください",
    searchEvents: "イベントを検索...",
    cancel: "キャンセル",
    save: "保存",
    edit: "編集",
    delete: "削除",
    participants: "参加者",
    date: "日付:",
    location: "場所:",
    leaveEvent: "イベントを離れる",
    joinEvent: "イベントに参加",
    created: "作成:",
    noEventsFound: "イベントが見つかりません。最初のイベントを作成してください！",
    unableToLoadEvents: "イベントを読み込めません",
    eventChat: "イベントチャット",
    justNow: "たった今",
    enterEventName: "イベント名を入力",
    enterLocation: "場所を入力（オプション）",
    enterEventDescription: "イベントの説明を入力（オプション）",
    eventDescription: "説明",
    dateAndTime: "日時",
    eventsTitle: "イベント",

    // Game
    gameInstructions: "ゲーム",
    gameTitleCount: "ゲームタイトル",
    addGame: "ゲームを追加",
    addNewgame: "新しいゲームを追加",
    gameTitle: "タイトル",
    descriptionGame: "説明",
    gameLink: "ゲームリンク (URL)",
    gameImage: "ゲーム画像 (URL)",
    playNow: "今すぐプレイ",
    Nogamesfound: "ゲームが見つかりません。",
    


    // Post creation
    whatsOnYourMind: "何を考えていますか？",
    photoVideo: "写真/ビデオ",
    camera: "カメラ",
    document: "ドキュメント",
    emoji: "絵文字",
    posting: "投稿中...",
    mediaAttached: "メディアが添付されました",
    maxFilesReached: "最大ファイル数に達しました",
    cameraActive: "カメラがアクティブ",
    switch: "切り替え",
    capture: "キャプチャ",
    searchEmoji: "絵文字を検索...",
    loginRequired: "投稿するにはログインしてください",
    loginToReact: "リアクションするにはログインしてください",
    loginToAddFriend: "友達リクエストを送るにはログインしてください",
    loginToFollow: "フォローするにはログインしてください",
    loginToMessenger: "メッセージを使うにはログインしてください",
    loginToSettings: "アカウント設定を変更するにはログインしてください",
    loginToPrivateSettings:
      "プライバシー・通知・セキュリティ設定を変更するにはログインしてください",
    settingGuestHint:
      "テーマ・言語・アクセシビリティは変更できます。アカウント設定にはログインが必要です。",
    settingLockedTitle: "ログインが必要です",
    settingLockedDescription: "この項目はログイン後に利用できます。",
    loginToViewFriends: "友達リストを見るにはログインしてください",
    loginToViewFriendRequests: "フレンドリクエストを見るにはログインしてください",
    guestFriendsHint:
      "ThoDevのユーザーを検索できます。友達やリクエストを見るにはログインしてください。",
    loginToContinue: "続行するにはログインしてください",
    loginToastTitle: "未ログイン",
    loginToastDefaultDesc: "データを同期するにはThoDevにログインしてください",
    contentOrMediaRequired: "コンテンツを入力するかメディアを添付してください",
    maxFilesLimit: "投稿あたり最大5ファイル",
    postSuccess: "投稿が作成されました",
    postError: "投稿作成エラー",
    cloudinaryConfigMissing: ".envにCloudinary設定がありません",
    photoCaptured: "写真が撮影され、投稿に追加されました",
    cameraError: "カメラを開けません。権限を確認してください",
    uploadFailed: "アップロード失敗: ",
    switchCamera: "カメラを切り替え",
    capturePhoto: "写真を撮影",
    attachedMedia: "添付メディア",
    limitReached: "制限に達しました",
    unsupportedFormat: "サポートされていない形式: ",
    fileTooLarge: "ファイルが大きすぎます ",
    close: "閉じる",

    // Error messages
    error: "エラー",
    success: "成功",
    warning: "警告",
    info: "情報",

    // Loading states
    loadingText: "読み込み中...",
    saving: "保存中...",
    deleting: "削除中...",

    // Profile specific
    userNotFound: "ユーザーが見つかりません",
    youHaventPostedYet: "まだ投稿していません",
    noPostsYet: "まだ投稿がありません",
    failedToSendFriendRequest: "友達リクエストの送信に失敗しました。",
    friendRequestSentTo: "{name}に友達リクエストを送信しました！",

    // Sidebar
    logout: "ログアウト",
    logoutSuccess: "ログアウトしました",
    logoutFailed: "ログアウト失敗: ",
    openMenu: "メニューを開く",
    closeMenu: "メニューを閉じる",
    expandSidebar: "サイドバーを展開",
    collapseSidebar: "サイドバーを折りたたむ",

    // Store/Market
    storeTitle: "THODEV MARKET",
    searchProducts: "欲しい商品を検索...",
    cart: "カート",
    orders: "注文",
    sellerChannel: "販売者チャンネル",
    categories: "カテゴリ",
    allProducts: "すべての商品",
    latestProducts: "最新の商品",
    categoryTitle: "カテゴリ: {category}",
    productCount: "{count} 個の商品",
    noProductsFound: "一致する商品が見つかりません。",
    hot: "HOT",
    viewDetails: "詳細を見る",
    loadingOrders: "注文を読み込み中...",
    myOrders: "マイ注文",
    all: "すべて",
    noOrdersInSection: "このセクションに注文がありません。",
    shopNow: "今すぐショッピング",
    buyAgain: "再購入",
    categoryLabel: "カテゴリ:",
    default: "デフォルト",
    quantity: "数量:",
    totalAmount: "合計:",
    pending: "保留中",
    shipped: "発送済み",
    delivered: "配達済み",
    cancelled: "キャンセル済み",

    addCart: "カートに追加",
    byNow: "今すぐ購入",
    numberProduct: "商品の数",
    review: "レビュー",
    notReviewForProduct: "この商品のレビューはありません",
    genuine: "本物の商品",
    nationwideDelivery: "全国配達",
    evaluate: "評価する",
    sold: "販売済み",
    outOfStock: "在庫切れ",
    product: "商品",
  },
};

export const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => localStorage.getItem("language") || "vi");

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
